/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LabRouteImport } from './routes/lab'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabRoiCalculationGuideRouteImport } from './routes/lab.roi-calculation-guide'
import { Route as LabB2bSaasCroGuideRouteImport } from './routes/lab.b2b-saas-cro-guide'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoiCalculationGuideRoute = LabRoiCalculationGuideRouteImport.update({
  id: '/roi-calculation-guide',
  path: '/roi-calculation-guide',
  getParentRoute: () => LabRoute,
} as any)
const LabB2bSaasCroGuideRoute = LabB2bSaasCroGuideRouteImport.update({
  id: '/b2b-saas-cro-guide',
  path: '/b2b-saas-cro-guide',
  getParentRoute: () => LabRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnostic': typeof DiagnosticRoute
  '/lab': typeof LabRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/lab/b2b-saas-cro-guide': typeof LabB2bSaasCroGuideRoute
  '/lab/roi-calculation-guide': typeof LabRoiCalculationGuideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnostic': typeof DiagnosticRoute
  '/lab': typeof LabRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/lab/b2b-saas-cro-guide': typeof LabB2bSaasCroGuideRoute
  '/lab/roi-calculation-guide': typeof LabRoiCalculationGuideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/diagnostic': typeof DiagnosticRoute
  '/lab': typeof LabRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/lab/b2b-saas-cro-guide': typeof LabB2bSaasCroGuideRoute
  '/lab/roi-calculation-guide': typeof LabRoiCalculationGuideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/diagnostic'
    | '/lab'
    | '/sitemap.xml'
    | '/admin'
    | '/lab/b2b-saas-cro-guide'
    | '/lab/roi-calculation-guide'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/diagnostic'
    | '/lab'
    | '/sitemap.xml'
    | '/admin'
    | '/lab/b2b-saas-cro-guide'
    | '/lab/roi-calculation-guide'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/diagnostic'
    | '/lab'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/lab/b2b-saas-cro-guide'
    | '/lab/roi-calculation-guide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiagnosticRoute: typeof DiagnosticRoute
  LabRoute: typeof LabRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/roi-calculation-guide': {
      id: '/lab/roi-calculation-guide'
      path: '/roi-calculation-guide'
      fullPath: '/lab/roi-calculation-guide'
      preLoaderRoute: typeof LabRoiCalculationGuideRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/b2b-saas-cro-guide': {
      id: '/lab/b2b-saas-cro-guide'
      path: '/b2b-saas-cro-guide'
      fullPath: '/lab/b2b-saas-cro-guide'
      preLoaderRoute: typeof LabB2bSaasCroGuideRouteImport
      parentRoute: typeof LabRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LabRouteChildren {
  LabB2bSaasCroGuideRoute: typeof LabB2bSaasCroGuideRoute
  LabRoiCalculationGuideRoute: typeof LabRoiCalculationGuideRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabB2bSaasCroGuideRoute: LabB2bSaasCroGuideRoute,
  LabRoiCalculationGuideRoute: LabRoiCalculationGuideRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DiagnosticRoute: DiagnosticRoute,
  LabRoute: LabRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
